# Generated by Django 2.2.12 on 2020-05-08 19:21

import compare.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problemID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('problemInfo', models.TextField(verbose_name='Problem Details')),
                ('evaluationCode', models.TextField(verbose_name='Evaluation Code')),
                ('isValid', models.BooleanField(default=False, verbose_name='Valid?')),
                ('isReleased', models.BooleanField(default=False, verbose_name='Released?')),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('dateSubmitted', models.DateField(auto_now_add=True)),
                ('localUser', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('solutionID', models.AutoField(primary_key=True, serialize=False)),
                ('solutionCode', models.TextField(verbose_name='Solution')),
                ('isVerified', models.BooleanField(default=False)),
                ('dateSubmitted', models.DateField(auto_now_add=True)),
                ('localUser', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('dataID', models.AutoField(primary_key=True, serialize=False)),
                ('dataset', models.FileField(upload_to='datasets/', validators=[compare.validators.validate_file])),
                ('datasetDesc', models.CharField(max_length=100, verbose_name='Dataset Short Description')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Problem')),
            ],
        ),
    ]
